FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker.io docker-compose

# Add Jenkins user to docker group
RUN groupadd docker || true
RUN usermod -aG docker jenkins

USER jenkins