spring.application.name=order-service


spring.datasource.url=jdbc:postgresql://postgres:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

server.port=8082

spring.kafka.bootstrap-servers=kafka:9092

# producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
# consumer (future use)
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.topic.name=order-topic-v2