server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**

        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/orders/**

        - id: inventory-service
          uri: http://inventory-service:8083
          predicates:
            - Path=/inventory/**

        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/payment/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always